<?php
// Delete options since ver.1.4 or older
delete_option('ez_zenback_closed_comment');
delete_option('ez_zenback_accuracy');
delete_option('ez_zenback_style_enable');
delete_option('ez_before_post');
delete_option('ez_before_post_home');
delete_option('ez_before_post_single');
delete_option('ez_before_post_page');
delete_option('ez_before_post_category');
delete_option('ez_before_post_search');
delete_option('ez_before_post_archive');
delete_option('ez_after_post');
delete_option('ez_after_post_home');
delete_option('ez_after_post_single');
delete_option('ez_after_post_page');
delete_option('ez_after_post_category');
delete_option('ez_after_post_search');
delete_option('ez_after_post_archive');
?>